# Plugins
plugins:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "2021 WHOSE PARTY - 資管 X 物治 X 護理 三系聯合宿營"
email: "ptimnur2021@gmail.com"
description: "Oct. 23 ~ Oct. 24 | Join us!"
baseurl: "https://ntu.im/whoseparty"
url: ""
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-43643469-5"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "2021 WHOSE PARTY"
organizerAlternateName: "2021WHOSE PARTY Camp"
organizerDescription: "2021 WHOSE PARTY - 台大 資管 X 物治 X 護理 三系聯合宿營籌備團隊"
organizerEmail: "ptimnur2021@gmail.com"
organizerLogo: "/img/favicons/favicon-2.png"
organizerLink: "https://ntu.im/whoseparty"

# Head
metaKeywords: "whose party, 2021 whose party, event, 臺大, 宿營, 台大, 臺大護理 x 臺大資管 x 臺大物治聯合宿營, NTU, IM, PT, NUR, 國立台灣大學, 國立臺灣大學, 資管, 護理, 物治, 聯合宿營, 迎新宿營, 迎新, 資訊管理學系迎新, 資訊管理學系宿營, 護理學系宿營, 護理學系迎新, 物理治療學系宿營, 物理治療學系迎新"
twitterAccount: ""
socialImageSrcGooglePlus: "/img/people/webicon.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
# c4pUrl: "https://bit.ly/dfua-c4p"
# c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "首頁"}
 - {permalink: "/news/", text: "最新消息"}
 - {permalink: "/schedule/", text: "活動時程"}
 - {permalink: "/crew/", text: "團隊介紹"}
 - {permalink: "/team/", text: "小隊資訊"}
 - {permalink: "/download/", text: "下載區"}
 - {permalink: "/faq/", text: "FAQ"}
# bottomNavigationLinks:
#  - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}
# rightNavigationButtons:
#  - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}

# Hero Block
heroImage: "crimson1.jpg"
heroTitle: "WHOSE PARTY"
heroTitle2: "2021 三系聯合迎新宿營"
eventDate: "Oct. 23 ~ Oct. 24"
typeoutTextValues: '"", "資訊管理學系x", "資訊管理學系x物理治療學系x", "資訊管理學系x物理治療學系x護理學系", "護理學系x", "護理學系x物理治療學系x", "護理學系x物理治療學系x資訊管理學系", "物理治療學系x", "物理治療學系x護理學系x", "物理治療學系x護理學系x資訊管理學系", "資訊管理學系x", "資訊管理學系x護理學系","資訊管理學系x護理學系x物理治療學系", "護理學系x", "護理學系x資訊管理學系x", "護理學系x資訊管理學系x物理治療學系", "物理治療學系x", "物理治療學系x資訊管理學系x", "物理治療學系x資訊管理學系x護理學系"'
typeoutFallback: "資訊管理學系x物理治療學系x護理學系"
heroButtons:
#  - {permalink: "/news/", text: "了解我們"}
#  - {permalink: "", text: "現在報名"}

# About Block
aboutTitle: "參與科系"
aboutImage: "night.png"
aboutBlock:
 - {title: "物理治療學系", image: "ntu_pt.jpg", text: "" }
 - {title: "資訊管理學系", image: "ntu_im.png", text: "" }
 - {title: "護理學系", image: "ntu_nur.jpg", text: "" }

# Statistic Block
statisticBlockImage: "statistic1.jpg"
statisticBlock:
 - {count: "3", specialCharacter: "", info: "參與科系", detail: ""}
 - {count: "100", specialCharacter: "+", info: "工人", detail: ""}
 - {count: "500", specialCharacter: "+", info: "準備時間", detail: ""}
 - {count: "10", specialCharacter: "+", info: "精彩活動", detail: ""}

# Latest News Block
# latestNewsTitle: ""

# Story Block
storyTitle: "故事概要"
storyButtonText: "點我看八大家族介紹"
storyButtonText_2: "點我看完整莊園故事"
storyImage: "city.jpg"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers1.jpg"
rockstarSpeakersCount: 6
rockstarSpeakersTitle: "認識召部"
rockstarSpeakersButtonText: "點我看團隊介紹"

# Location Block
# locationBlockTitle: "舉辦地點"
# eventLocationName: "埔心牧場"
# eventLocationLink: "https://www.pushin-ranch.com/"
# eventStreetAddress: "桃園市楊梅區幼獅路一段439號"
# eventAddressLocality: ""
# eventAddressLocalityRegion: ""
# eventPostalCode: ""
# eventAddressCountry: ""
# eventStartTime: ""
# eventDoorTime: ""
# eventEndTime: ""
# eventPlaceCoordinates: ""
# mapCenterCoordinates: ""
# mapMobileCenterCoordinates: ""

# Venue Block
venueImage: "deer.jpg"
venueBlockTitle: "活動地點"
venueBigImage: "pushin_1_1.jpg"
venueSmallImage1: "pushin_2.jpg"
venueSmallImage2: "pushin_4_1.jpg"
venueSmallImage3: "pushin_5.jpg"
venueTitle: "埔心牧場"
venueFeatures: ["桃園市楊梅區幼獅路一段439號","03 464 4132"]

# Tweets Feed Block
# tweetsFeedImage: "twitter-feed.jpg"
# tweetsFeedTitle: "What's Up?"
# twitterHashTag: "IMxPTxNUR"
# twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
partnersImage: "neon.webp"
organizersTitle: "主辦單位"
partnersTitle: ""
partnersC4sponsorsButton: ""

# Sponsors Block
sponsorTitle: "合作夥伴"
sponsorImage: "night.png"
sponsorButtonText: "點我看完整贊助名單"
sponsorBlock:

 - {title: "雪坊優格", image: "logo1.png", url: "sponsor_intro_1.html" }
 - {title: "BAR BEER", image: "logo2.png", url: "sponsor_intro_2.html" }
 - {title: "ONEWAY CAFE", image: "logo3.jpg", url: "sponsor_intro_3.html" }
 - {title: "京阪豚骨拉麵", image: "logo4.jpg", url: "sponsor_intro_4.html" }
 - {title: "轉轉義大利麵", image: "logo5.jpg", url: "sponsor_intro_5.html" }
sponsorBlock_minor:
 - {title: "雪坊優格", image: "logo1.png", url: "sponsor_intro_1.html" }
 - {title: "BAR BEER", image: "logo2.png", url: "sponsor_intro_2.html" }
 - {title: "oneway cafe", image: "logo3.jpg", url: "sponsor_intro_3.html" }
 - {title: "京阪豚骨拉麵", image: "logo4.jpg", url: "sponsor_intro_4.html" }
 - {title: "轉轉義大利麵", image: "logo5.jpg", url: "sponsor_intro_5.html" }
 - {title: "七里亭", image: "logo6.jpg", url: "" }
 - {title: "人性空間", image: "logo7.jpg", url: "" }
 - {title: "小飯廳", image: "logo8.jpg", url: "" }
 - {title: "左巴好室", image: "logo10.jpg", url: "" }
 - {title: "台一牛奶大王", image: "logo9.jpg", url: "" }
 - {title: "溏老鴨小火鍋", image: "logo17.jpg", url: "" }
 - {title: "金湯匙豆花", image: "logo14.jpg", url: "" }
 - {title: "香料廚房", image: "logo15.jpg", url: "" }
 - {title: "Lazy thai", image: "logo21.jpg", url: "" }
 - {title: "yu poke", image: "logo22.png", url: "" }
 - {title: "蘇草", image: "logo19.jpg", url: "" }
 - {title: "好想吃冰", image: "logo11.jpg", url: "" }
 - {title: "安好食", image: "logo12.jpg", url: "" }
 - {title: "搗飛豆花", image: "logo16.jpg", url: "" }
 - {title: "希臘左巴", image: "logo13.jpg", url: "" }
 - {title: "韓庭州", image: "logo18.jpg", url: "" }
 - {title: "barkers美式餐廳", image: "logo20.jpg", url: "" }
# Subscribe Block
# subscribeImage: "subscribe.jpg"
# subscribeTitle: "在此報名"
# subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
# subscribeInfo: ""

# Tickets Block
ticketsImage: "green.jpg"
ticketsTitle: " 在此報名"
ticketsInfo: ""
ticketReminderList: ["報名資格：全體台大物治、資管及護理系大一新生","活動日期：10/23～24","活動地點：埔心牧場", "匯款資訊<br>帳戶：007005725407<br>戶名：林郁傑<br>銀行：005-土地銀行", "請注意報名期限及繳費期限，逾時不候！","宿營防疫規劃及其他資訊可參考FAQ說明，也歡迎直接聯絡我們喔！", "<br>"]
ticketsOffers:
 -
  name: "報名連結"
  price: "2,900"
  priceCurrency: "NT$  "
  #ticketsNumber: "300"
  #buyButtonLink: "{{site.baseurl}}/applicationform"
  buyButtonText: "點我報名"
  ticketContentList: ["報名期限至 9/29 23:59 止", "繳費期限至 9/30 23:59 止"]
  validFrom: "2021-09-01T09:00"
  validThrough: "2021-09-29T23:59"
  soldOut: false
  disabled: false
  soldOutText: "--報名已截止--"

#  -
#   name: "台大集合"
#   price: "$$$"
#   priceCurrency: "NT$  "
#   ticketsNumber: "150"
#   ribbon: "台大集合"
#   buyButtonLink: "http://dfua.ticketforevent.com/"
#   buyButtonText: "點我報名"
#   # additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
#   ticketContentList: ["台大搭乘遊覽車出發！", "期限至 止"]
#   validFrom: "2021-09-02T09:00"
#   validThrough: "2021-09-30T23:59"
#   soldOut: true
#   disabled: true
#   soldOutText: "--報名已截止--"

# Footer
socialLinks:
  # - {link: "https://plus.google.com/b/102444623953913144164", icon: "google-plus"}
  # - {link: "https://twitter.com/intent/user?screen_name=GDGLviv", icon: "twitter"}
  - {link: "https://facebook.com/GDGLviv", icon: "facebook"}
  - {permalink: "/feed.xml", icon: "rss"}

footerBlocks:
  - title: "宿營夥伴"
    links:
      - {permalink: "/sponsorsList", text: "完整贊助名單"}
      - {permalink: "/assets/proposal.pdf", text: "合作辦法說明"}
      - {link: "https://www.mc.ntu.edu.tw/nursing/Index.action", text: "台大護理學系"}
      - {link: "https://www.mc.ntu.edu.tw/ntupt/Index.action", text: "台大物理治療學系"}
      - {link: "https://management.ntu.edu.tw/IM", text: "台大資訊管理學系"}
      - {link: "https://www.pushin-ranch.com/", text: "埔心牧場"}
      # - {link: "http://gdg.org.ua", text: "點我進入贊助頁面"}

  - title: "常用連結"
    links:
      - {link: "https://ceiba.ntu.edu.tw/student/index.php", text: "NTU CEIBA"}
      - {link: "https://cool.ntu.edu.tw/", text: "NTU COOL"}
      - {link: "https://if192.aca.ntu.edu.tw/index.php", text: "臺大選課系統" }
      - {link: "https://nol.ntu.edu.tw/nol/guest/index.php", text: "臺大課程網"}
      - {link: "https://www.cc.ntu.edu.tw/chinese/index.asp", text: "臺大計算機及資訊網路中心"}
      - {link: "https://pdogs.ntu.im/judge/", text: "PDOGS"}
      - {link: "https://www.facebook.com/groups/ntucmnursing/?ref=share", text: "台大護理系交流版"}

  - title: "聯絡資訊"
    links:
      - {link: "tel:+886939818275", text: "物理治療學系窗口：傅彥齊"}
      - {link: "tel:+886987953881", text: "資訊管理學系窗口：吳宇璇"}
      - {link: "tel:+886966570258", text: "護理學系窗口：陳怡靜"}
      - {link: "mailto:ptimnur2021@gmail.com", text: "2021 WHOSE PARTY 臺大護理物治資管聯合迎新宿營 官方信箱"}


  # - title: "重點專區"
    # links:
      # - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
# blogTitle: "Latest news"
# blogCommentsEnabled: true
# discusShortName: "devfestua"

# Speakers List Block
showSessions: true

# Team Block
# teamBlockTitle: "About us"
# aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."

# Logistics Find Way Block
# findWayTitle: "Find your way here"
# findWayDistance: "Distance"
# findWayDriving: "DRIVING"
# findWayWalking: "WALKING"
# findWayBicycling: "BICYCLING"
# findWayTransit: "TRANSIT"
# findWayFindFlight: "Find Flight"
# logisticsMapCenterCoordinates: "49.056728, 3.117289"
# logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
# logisticsMapAutoDirections: false

# Logistics Direction Details Block
# directionDetailsImage: "direction-details.jpg"
# directionDetailsTitle: "Get around Lviv"
# directionDetailsCards:
#  - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
#  - {title: "Public Transit", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
#  - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
# directionDetailsWideCards:
#  -
#   title: "Questions?"
#   subCards:
#    -
#     title: "Hotels"
#     links:
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
#    -
#     title: "Registration"
#     links:
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
  #  -
  #   title: "Attendance Details"
  #   links:
  #    - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
  #    - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
  #    - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
  #    - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
# hackathonTitle: "Hackathon"
# enableHackathon: true

# Hackathon About Block
# aboutHackathonTitle: "Meet our themes"
# hackathonRows:
#  - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
#  - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
#  - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
# judgesImage: "judges.jpg"
# judgesTitle: "Judges"

# Hackathon Prizes Block
# prizesTitle: "Prizes"
# prizes:
#  - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
#  - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
#  - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
# hackathonLocationBlockTitle: "Location"
# hackathonLocationName: "Communa"
# hackathonLocationLink: "http://communa.net.ua/"
# hackathonStreetAddress: "1 Halytska St"
# hackathonAddressLocality: "Lviv"
# hackathonAddressLocalityRegion: "Lvivska"
# hackathonPostalCode: "79000"
# hackathonAddressCountry: "Ukraine"
# hackathonTimeTitle: "Hack through"
# hackathonStartTime: "2014-10-24T10:00"
# hackathonDoorTime: "09:00"
# hackathonEndTime: "2014-10-25T00:00"
# viewOnMap: "View on Google Maps"
# hackathonPlaceCoordinates: "49.840999, 24.031144"
# hackathonMapCenterCoordinates: "49.840696, 24.028754"
# hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
